# Generated by Django 5.2.7 on 2026-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
