# Generated by Django 5.2.7 on 2026-04-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ats_threshold',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='job',
            name='threshold_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
